async function main(): Promise<void> {
    console.log("Hello, world!");
}

main()
    .then(() => {})
    .catch((err) => {
        console.error(err);
    });